global using System.Collections.Immutable;
global using System.Text.Json;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Hosting;
global using Microsoft.Extensions.Logging;
global using Microsoft.Extensions.Options;
global using Refit;
global using TubePlayer.Business;
global using TubePlayer.Business.Models;
global using TubePlayer.Models;
global using TubePlayer.Presentation;
global using TubePlayer.Services;
global using TubePlayer.Services.Models;
global using ApplicationExecutionState = Windows.ApplicationModel.Activation.ApplicationExecutionState;
